### ISSUE TITLE
Add change tracking for model collection services

### ISSUE THREAD

**Issue by hoeyi** [hoeyi/NjordinSight#197]
### Summary ###
Currently, change tracking does not support updates and creates inefficient database queries by updating records that do not require it. Add change tracking for adds, updates, and deletes so that the service layer can execute database actions more efficiently.

### Acceptance Criteria ###
- [x] Additions to the loaded collection
- [x] Removals from the loaded collection
- [x] Updates to entries in the current collection, less those added in the same session. 

### Additional Context ###
Change tracking for updates usually involves implementing `INotifyPropertyChanged`. Do this in the DTO classes since those the ones that are bound to views.

**Comment by hoeyi** [comment]
Originally the thought was to keep the implementation of `INotifyPropertyChanged` in the entity model classes, but this adds complexity and muddies the purpose of the entity model classes. Instead, add changing tracking to the DTOs. The client may benefit from having changing tracking, as well.
